[package]
name = "launcher"
version = "0.1.0"
edition = "2024"
description = "Laucher for the app, run in background, always have admin priviledge"
license = "UNLICENSED"

[dependencies]
shared_libs = { path = "../shared_libs" }
tokio = { workspace = true }
log = { workspace = true }
ed25519-dalek = { workspace = true }
base64 = { workspace = true }

[package.metadata.deb]
name = "Gsoft_Device_Agent-launcher"
depends = "$auto"
section = "utility"
maintainer-scripts = "debian/"
assets = [ #: Have to sync up with 'crates/shared_libs/src/path/linux.rs'
    # [Source path, Target path in OS, Permissions]
    ["target/release/launcher", "opt/gsoft-agent/launcher", "755"],
    ["target/release/main_worker", "opt/gsoft-agent/main_worker", "755"],
    ["gsoft-agent.service", "lib/systemd/system/gsoft-agent.service", "644"],
]
