[package]
name = "main_worker"
version = "0.3.3"
edition = "2024"
description = "Device Agent main logic"

[dependencies]
shared_libs = { path = "../shared_libs" }
all-smi = { workspace = true }
chrono = { workspace = true }
flexi_logger = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
ureq = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
smbios-lib = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
wmi = { workspace = true }
winreg = { workspace = true }
windows-sys = { workspace = true }