[package]
name = "shared_libs"
version = "0.1.0"
edition = "2024"

[features]
default = ["local_workspace"] #! Use local workspace path for debug instead of deploy OS system path
local_workspace = []

[dependencies]
all-smi = { workspace = true }
chrono = { workspace = true }
flexi_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sysinfo = { workspace = true }