[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["NgTrDat <trongdat4work@gmail.com>"]
description = "Gsoft Device Agent: multi-binary app to gather static and dynamic information for monitoring and maintenance corporation own device"
edition = "2024"

[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Link-time optimization (makes a huge difference)
codegen-units = 1   # Slower compile time, smaller binary
strip = true        # Strip symbols from the binary
panic = 'abort'     # Removes panic unwinding overhead
