#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl daemon-reload || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /opt/gsoft-agent || true
    rm -rf /var/log/gsoft-agent || true
    userdel gsoft-agent || true
fi