#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl daemon-reload || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /opt/rust-agent || true
    rm -rf /var/log/rust-agent || true
    userdel rust-agent || true
fi